# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r		 


r:
  - release


r_packages:
  - covr
  - roxygen2
  - rmarkdown
  - stringr
  - sp
  - raster
  - htmlwidgets
  - htmltools
  - rgdal
  - rgeos
  - gdalUtils
  - geosphere
  - tools
  - maptools
  - log4r
  - zoo
  - data.table
  - spatial.tools
  - devtools
  - sf
  - methods
  - brew



addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - saga 
      - grass
      - otb-bin
      - libnetcdf-dev
      - libgeos-dev
      - libproj-dev
      - libgdal-dev
      - netcdf-bin 
      - libudunits2-dev

